# -*- coding: utf-8 -*-

from ttab.loads.datasets.dataset_shifts import SyntheticShiftProperty
from ttab.scenarios import HomogeneousNoMixture, Scenario, TestDomain, TestCase

"""define a dict of scenarios."""


default_scenarios = {
    # "S1": Scenario(
    #     task="classification",
    #     model_name="resnet20",
    #     model_adaptation_method="tent",
    #     model_selection_method="last_iterate",
    #     base_data_name="cifar10",
    #     test_domains=[
    #         TestDomain(
    #             base_data_name="cifar10",
    #             data_name="cifar10_c_deterministic-gaussian_noise-5",
    #             shift_type="synthetic",
    #             shift_property=SyntheticShiftProperty(
    #                 shift_degree=5,
    #                 shift_name="gaussian_noise",
    #                 version="deterministic",
    #                 has_shift=True,
    #             ),
    #             domain_sampling_name="uniform",
    #             domain_sampling_value=None,
    #             domain_sampling_ratio=1.0,
    #         )
    #     ],
    #     test_case=TestCase(
    #         inter_domain=HomogeneousNoMixture(has_mixture=False),
    #         batch_size=128,
    #         data_wise="batch_wise",
    #         offline_pre_adapt=False,
    #         episodic=False,
    #         intra_domain_shuffle=True,
    #     ),
    # ),
    # "S2": Scenario(
    #     task="classification",
    #     model_name="resnet20",
    #     model_adaptation_method="bn_adapt",
    #     model_selection_method="last_iterate",
    #     base_data_name="cifar10",
    #     test_domains=[
    #         TestDomain(
    #             base_data_name="cifar10",
    #             data_name="cifar10_c_deterministic-gaussian_noise-5",
    #             shift_type="synthetic",
    #             shift_property=SyntheticShiftProperty(
    #                 shift_degree=5,
    #                 shift_name="gaussian_noise",
    #                 version="deterministic",
    #                 has_shift=True,
    #             ),
    #             domain_sampling_name="uniform",
    #             domain_sampling_value=None,
    #             domain_sampling_ratio=1.0,
    #         )
    #     ],
    #     test_case=TestCase(
    #         inter_domain=HomogeneousNoMixture(has_mixture=False),
    #         batch_size=128,
    #         data_wise="batch_wise",
    #         offline_pre_adapt=False,
    #         episodic=False,
    #         intra_domain_shuffle=True,
    #     ),
    # ),
    # "S3": Scenario(
    #     task="classification",
    #     model_name="resnet20",
    #     model_adaptation_method="memo",
    #     model_selection_method="last_iterate",
    #     base_data_name="cifar10",
    #     test_domains=[
    #         TestDomain(
    #             base_data_name="cifar10",
    #             data_name="cifar10_c_deterministic-gaussian_noise-5",
    #             shift_type="synthetic",
    #             shift_property=SyntheticShiftProperty(
    #                 shift_degree=5,
    #                 shift_name="gaussian_noise",
    #                 version="deterministic",
    #                 has_shift=True,
    #             ),
    #             domain_sampling_name="uniform",
    #             domain_sampling_value=None,
    #             domain_sampling_ratio=1.0,
    #         )
    #     ],
    #     test_case=TestCase(
    #         inter_domain=HomogeneousNoMixture(has_mixture=False),
    #         batch_size=1,
    #         data_wise="sample_wise",
    #         offline_pre_adapt=False,
    #         episodic=False,
    #         intra_domain_shuffle=True,
    #     ),
    # ),
    # "S4": Scenario(
    #     task="classification",
    #     model_name="resnet20",
    #     model_adaptation_method="shot",
    #     model_selection_method="last_iterate",
    #     base_data_name="cifar10",
    #     test_domains=[
    #         TestDomain(
    #             base_data_name="cifar10",
    #             data_name="cifar10_c_deterministic-gaussian_noise-5",
    #             shift_type="synthetic",
    #             shift_property=SyntheticShiftProperty(
    #                 shift_degree=5,
    #                 shift_name="gaussian_noise",
    #                 version="deterministic",
    #                 has_shift=True,
    #             ),
    #             domain_sampling_name="uniform",
    #             domain_sampling_value=None,
    #             domain_sampling_ratio=1.0,
    #         )
    #     ],
    #     test_case=TestCase(
    #         inter_domain=HomogeneousNoMixture(has_mixture=False),
    #         batch_size=64,
    #         data_wise="batch_wise",
    #         offline_pre_adapt=True,
    #         episodic=False,
    #         intra_domain_shuffle=True,
    #     ),
    # ),
    # "S5": Scenario(
    #     task="classification",
    #     model_name="resnet20",
    #     model_adaptation_method="t3a",
    #     model_selection_method="last_iterate",
    #     base_data_name="cifar10",
    #     test_domains=[
    #         TestDomain(
    #             base_data_name="cifar10",
    #             data_name="cifar10_c_deterministic-gaussian_noise-5",
    #             shift_type="synthetic",
    #             shift_property=SyntheticShiftProperty(
    #                 shift_degree=5,
    #                 shift_name="gaussian_noise",
    #                 version="deterministic",
    #                 has_shift=True,
    #             ),
    #             domain_sampling_name="uniform",
    #             domain_sampling_value=None,
    #             domain_sampling_ratio=1.0,
    #         )
    #     ],
    #     test_case=TestCase(
    #         inter_domain=HomogeneousNoMixture(has_mixture=False),
    #         batch_size=64,
    #         data_wise="batch_wise",
    #         offline_pre_adapt=False,
    #         episodic=False,
    #         intra_domain_shuffle=True,
    #     ),
    # ),
    # "S6": Scenario(
    #     task="classification",
    #     model_name="resnet26",
    #     model_adaptation_method="ttt",
    #     model_selection_method="last_iterate",
    #     base_data_name="cifar10",
    #     test_domains=[
    #         TestDomain(
    #             base_data_name="cifar10",
    #             data_name="cifar10_c_deterministic-gaussian_noise-5",
    #             shift_type="synthetic",
    #             shift_property=SyntheticShiftProperty(
    #                 shift_degree=5,
    #                 shift_name="gaussian_noise",
    #                 version="deterministic",
    #                 has_shift=True,
    #             ),
    #             domain_sampling_name="uniform",
    #             domain_sampling_value=None,
    #             domain_sampling_ratio=1.0,
    #         )
    #     ],
    #     test_case=TestCase(
    #         inter_domain=HomogeneousNoMixture(has_mixture=False),
    #         batch_size=1,
    #         data_wise="sample_wise",
    #         offline_pre_adapt=False,
    #         episodic=False,
    #         intra_domain_shuffle=True,
    #     ),
    # ),
    # "S7": Scenario(
    #     task="classification",
    #     model_name="resnet50",
    #     model_adaptation_method="ttt_plus_plus",
    #     model_selection_method="last_iterate",
    #     base_data_name="cifar10",
    #     test_domains=[
    #         TestDomain(
    #             base_data_name="cifar10",
    #             data_name="cifar10_c_deterministic-gaussian_noise-5",
    #             shift_type="synthetic",
    #             shift_property=SyntheticShiftProperty(
    #                 shift_degree=5,
    #                 shift_name="gaussian_noise",
    #                 version="deterministic",
    #                 has_shift=True,
    #             ),
    #             domain_sampling_name="uniform",
    #             domain_sampling_value=None,
    #             domain_sampling_ratio=1.0,
    #         )
    #     ],
    #     test_case=TestCase(
    #         inter_domain=HomogeneousNoMixture(has_mixture=False),
    #         batch_size=128,
    #         data_wise="batch_wise",
    #         offline_pre_adapt=True,
    #         episodic=False,
    #         intra_domain_shuffle=True,
    #     ),
    # ),
    # "S8": Scenario(
    #     task="classification",
    #     model_name="resnet26",
    #     model_adaptation_method="no_adaptation",
    #     model_selection_method="last_iterate",
    #     base_data_name="cifar10",
    #     test_domains=[
    #         TestDomain(
    #             base_data_name="cifar10",
    #             data_name="cifar10_c_deterministic-gaussian_noise-5",
    #             shift_type="synthetic",
    #             shift_property=SyntheticShiftProperty(
    #                 shift_degree=5,
    #                 shift_name="gaussian_noise",
    #                 version="deterministic",
    #                 has_shift=True,
    #             ),
    #             domain_sampling_name="uniform",
    #             domain_sampling_value=None,
    #             domain_sampling_ratio=1.0,
    #         )
    #     ],
    #     test_case=TestCase(
    #         inter_domain=HomogeneousNoMixture(has_mixture=False),
    #         batch_size=64,
    #         data_wise="batch_wise",
    #         offline_pre_adapt=False,
    #         episodic=False,
    #         intra_domain_shuffle=True,
    #     ),
    # ),
}
